export type XDirection = 'left' | 'right' | 'neutral';
export type YDirection = 'up' | 'down' | 'neutral';

export default abstract class InputComponent {
    #up: boolean;
    #down: boolean;
    #left: boolean;
    #right: boolean;
    #shoot: boolean;

    constructor() {
        this.reset();
    }

    reset() {
        this.#up = false;
        this.#down = false;
        this.#left = false;
        this.#right = false;
        this.#shoot = false;
    }

    get up() {
        return this.#up;
    }

    get down() {
        return this.#down;
    }

    get left() {
        return this.#left;
    }

    get right() {
        return this.#right;
    }

    get shoot() {
        return this.#shoot;
    }

    get xDirection(): XDirection {
        if (this.#left) {
            return 'left';
        } else if (this.#right) {
            return 'right';
        } else {
            return 'neutral';
        }
    }

    get yDirection(): YDirection {
        if (this.#up) {
            return 'up';
        } else if (this.#right) {
            return 'down';
        } else {
            return 'neutral';
        }
    }

    protected setXDirection(direction: XDirection) {
        this.#left = direction === 'left';
        this.#right = direction === 'right';
    }

    protected setYDirection(direction: YDirection) {
        this.#up = direction === 'up';
        this.#down = direction === 'down';
    }

    protected setShoot(isShootDown: boolean) {
        this.#shoot = isShootDown;
    }

    /**
     * Update method called automatically by a `GameObject` on every game step.
     * @param time The current timestamp as generated by the Request Animation Frame or SetTimeout.
     * @param delta The delta time, in ms, elapsed since the last frame.
     */
    abstract update(time: number, delta: number): void;
}
